apiVersion: v1
kind: Service
metadata:
  name: supercharged-test-service
spec:
  type: NodePort
  selector:
    app: supercharged-test
  ports:
  - protocol: TCP
    port: 80 # The port that the service exposes
    targetPort: 80 # The port that the container exposes
    nodePort: 30001 # Specify the NodePort (30000-32767)