name: React build and push artifact

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/superchargedtodo:v1
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/superchargedtodo:latest
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/superchargedtodo:v1,mode=max

