name: React build and push to Docker Hub

on:
    pull_request:
      branches: [ "main" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        sudo echo  testing the version number v1
        sudo docker build . --file Dockerfile1 --tag superchargedtest:v1
    - name: Login to Docker Hub
      run: sudo echo "${{ secrets.DOCKER_HUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
    - name: listing the Docker image
      run: sudo docker images -a
    - name: tagging the docker image name with respect to docker hub username
      run: sudo docker tag superchargedtest:v1 "${{ secrets.DOCKER_HUB_USERNAME }}"/superchargedtest:v1
    - name: Docker image name after tagging
      run: sudo docker images -a
    - name: Push the Docker image
      run: sudo docker push "${{ secrets.DOCKER_HUB_USERNAME }}"/superchargedtest:v1
    - name: delete the older docker image 
      run: sudo docker rmi -f superchargedtest:v1

#   test-docker-image:
#     runs-on: self-hosted
#     needs: build-docker-image
#     steps:
#     - name: stop any older docker container
#       run: for i in `sudo docker ps -a | grep nginx | awk '{print $1}'`; do sudo docker stop $i; done
#     - name: run the Docker image
#       run: sudo docker run -d -p 8080:8080 "${{ secrets.DOCKER_HUB_USERNAME }}"/nginx-web1:v1
    
#   ping-the-url:
#     runs-on: self-hosted
#     needs: test-docker-image
#     steps:
#     - name: ping the url
#       run: curl -i http://localhost:8080 | grep "HTTP/1.1 200 OK" > /dev/null 2>&1

  
